name: Build Android

on:
  push:
    branches: ["test"]
    paths:
      - ".github/**"
      - "lib/**"
      - "android/**"
      - "pubspec.yaml"
      - "pubspec.lock"
  pull_request:
    branches: ["test"]
    paths:
      - ".github/**"
      - "lib/**"
      - "android/**"
      - "pubspec.yaml"
      - "pubspec.lock"

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ${{ env.FLUTTER_HOME }}
        key: ubuntu-flutter-${{ env.FLUTTER_VERSION }}
        restore-keys: |
          ubuntu-flutter-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Cache Pub Packages
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ubuntu-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ubuntu-pub-

    - name: Cache build_runner (Optional)
      uses: actions/cache@v3
      with:
        path: .dart_tool/build
        key: ubuntu-build-runner-${{ hashFiles('**/*.dart') }}
        restore-keys: |
          ubuntu-build-runner-

    - name: Install dependencies
      run: flutter pub get

    - name: Prebuild with build_runner
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build APK and AAB
      run: |
        flutter build apk --debug
        # flutter build aab --debug

    - name: Upload Android Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "DPIP-Android"
        path: |
          build/app/outputs/flutter-apk/*.apk
          build/app/outputs/bundle/release/*.aab
