name: Build Android

on:
  push:
    branches: ["tset4"]
  pull_request:
    branches: ["tset4"]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            android:
              - 'android/**'
              - 'assets/**'
              - 'lib/**'
              - 'pubspec.yaml'

  Android:
    needs: changes
    if: ${{ needs.changes.outputs.android == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Cache Pub Packages
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Cache build_runner (Optional)
      uses: actions/cache@v3
      with:
        path: .dart_tool/build
        key: ${{ runner.os }}-build-${{ hashFiles('lib/api/model/**/*.dart') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Cache gradle and sdk
      uses: actions/cache@v3
      env:
        cache-name: cache-gradle-and-sdk
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/wrapper/gradle-wrapper.properties', '**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache Android sdk
      uses: actions/cache@v3
      env:
        cache-name: cache-Android-sdk
      with:
        path: |
          /usr/local/lib/android/sdk/platforms/android-31
          /usr/local/lib/android/sdk/platforms/android-33
        key: ${{ runner.os }}-android-platforms-${{ env.cache-name }}-${{ hashFiles('android/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: flutter pub get

    - name: Prebuild with build_runner
      run: dart run build_runner build

    - name: Build apk
      run: flutter build apk --debug

    - name: Upload (apk) Artifacts
      uses: actions/upload-artifact@main
      with:
        name: "DPIP.apk"
        path: build/app/outputs/flutter-apk/*.apk
