name: Build iOS

on:
  push:
    branches: ["tset4"]
  pull_request:
    branches: ["tset4"]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      ios: ${{ steps.filter.outputs.ios }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ios:
              - 'ios/**'
              - 'assets/**'
              - 'lib/**'
              - 'pubspec.yaml'

  iOS:
    needs: changes
    if: ${{ needs.changes.outputs.ios == 'true' }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Cache Pub Packages
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Cache build_runner (Optional)
      uses: actions/cache@v3
      with:
        path: .dart_tool/build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/api/model/**/*.dart') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Cache CocoaPods Pods
      uses: actions/cache@v3
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: ${{ runner.os }}-pods-

    - name: Install dependencies
      run: flutter pub get

    - name: Install iOS Pods
      run: |
        cd ios
        pod install

    - name: Prebuild with build_runner
      run: dart run build_runner build

    - name: Build iOS App and IPA
      run: |
        flutter build ios --debug --no-codesign --split-debug-info=build/symbols
        mkdir -p Payload
        cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
        zip -r DPIP.ipa Payload

    - name: Upload (app) Artifacts
      uses: actions/upload-artifact@main
      with:
        name: DPIP.app
        path: build/ios/iphoneos/Runner.app

    - name: Upload (ipa) Artifacts
      uses: actions/upload-artifact@main
      with:
        name: DPIP.ipa
        path: DPIP.ipa
